config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :articles do
    post :add_like, on: :member

    resources :comments, only: [:create, :destroy]
  end

  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # delete 'articles/:id', to: 'articles#destroy'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # patch 'articles/:id', to: 'articles#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }

  after_destroy :send_destroy_info

  has_many :comments, dependent: :destroy
  has_many :likes
  belongs_to :user

  has_attached_file :image, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def tags=(text)
    text.is_a?(String) ? super(sanitize_tags(text)) : super(text)
  end

  private

  def sanitize_tags(text)
    text.split.map(&:downcase).uniq
  end

  def send_destroy_info
    ArticleMailer.article_destroy_info(self).deliver
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, presence: true, email: true
  validates :body, presence: true, length: { in: 6..500 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :provide_article, only: [:show, :destroy, :edit, :update, :add_like]

  def index
    @articles = Article.all
                       .paginate(:page => params[:page], :per_page => 20)
                       .includes(:user)

    if params[:query].present?
      @articles = @articles.where("? = any(tags)", params[:query])
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to article_path(@article), notice: 'Pomyślnie utworzono artykuł'
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new(commenter: session[:commenter])
    @user_like = @article.likes.find_by(user: current_user)
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def add_like
    @article.likes.create(user: current_user)

    redirect_to article_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :tags, :image)
          .merge(user: current_user)
  end

  def provide_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :provide_article, only: [:create, :destroy]

  def create
    @comment = Comment.new(comment_params.merge(article: @article))
    if @comment.save
      session[:commenter] = @comment.commenter
      redirect_to article_path(@article)
    else
      render 'articles/show'
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy!

    redirect_to article_path(@article)
  end

  private

  def provide_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_errors.html.erb
<% if model.errors.any? %>
  <div>
    <h2>
      <%= pluralize(model.errors.count, 'error') %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/articles/_form.html.erb
<p>
  <%= link_to 'Back', articles_path, class: 'btn btn-default' %>
</p>

<%= render 'errors', model: @article %>

<%= form_for @article, html: { multipart: true } do |f| %>
  <div class='form-group'>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :tags %><br>
    <%= f.text_field :tags, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <p>
    <%= f.submit class: 'btn btn-success' %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<p>
  <%= link_to 'New article', new_article_path %>
</p>

<%= form_tag articles_path, method: :get do %>
  <div class="input-group">
    <%= text_field_tag :query, "", value: params[:query], class: "form-control" %>
    <span class="input-group-btn">
      <%= submit_tag "Search", class: "btn btn-default" %>
      <%= link_to "Clear", articles_path, class: "btn btn-danger" %>
    </span>
  </div>
<% end %>

<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

<table class='table table-hover'>
  <tr>
    <th>ID</th>
    <th>Created at</th>
    <th>Title</th>
    <th>Author</th>
    <th colspan='3'></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.created_at.to_date %></td>
      <td><%= article.title %></td>
      <td><%= article.user.email %></td>
      <td><%= link_to 'Show', article_path(article), class: 'btn btn-success' %></td>
      <td><%= link_to 'Destroy', article_path(article),
                                 method: :delete,
                                 data: { confirm: 'Are you sure?' },
                                 class: 'btn btn-danger' %>
      <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary' %></td>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= link_to '<---', articles_path %>
<%= link_to 'Edit', edit_article_path(@article) %>

<p>
  <%= image_tag @article.image.url, height: '150px', width: '250px' %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.user.email %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @article.tags.join(' ') %>
</p>

<p>
  <strong>Likes: </strong>
  <%= @article.likes.count %>
</p>

<% if @user_like.nil? %>
  <%= link_to 'LIKE', add_like_article_path(@article), method: :post %>
<% end %>

<h2>Comments</h2>
<%= render @article.comments.order(created_at: :desc) %>

<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Delete', article_comment_path(@article, comment),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
</p>
<hr>

app/views/comments/_form.html.erb
<h3>Add comment</h3>

<%= render 'errors', model: @comment %>

<%= form_for [@article, @comment] do |f| %>
  <div class='form-group'>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <p>
    <%= f.submit class: 'btn btn-success' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <% flash.each do |type, message| %>
      <div class='alert alert-warning'>
        <%= message %>
      </div>
    <% end %>

    <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default') %>
        (<%= current_user.email %>)
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>My app</h1>

<%= link_to 'My Blog', articles_path %>